#!/usr/bin/env python3
"""
Flash ESP32-S3 PhotoPainter firmware.

Reads flash arguments from build/flash_args (generated by idf.py build),
then invokes esptool from the IDF Python environment.

Usage:
    python3 flash.py [--port /dev/ttyACM0] [--baud 460800] [--no-monitor]

After flashing, optionally starts the serial monitor (monitor.py).
"""

import argparse
import os
import subprocess
import sys

IDF_PYTHON = os.path.expanduser(
    "~/.espressif/python_env/idf6.0_py3.13_env/bin/python"
)
BUILD_DIR = os.path.join(os.path.dirname(__file__), "build")
FLASH_ARGS_FILE = os.path.join(BUILD_DIR, "flash_args")


def read_flash_args():
    """Parse build/flash_args into a flat list of esptool arguments.

    build/flash_args is generated by ``idf.py build``.  Each line contains
    space-separated tokens that map directly to esptool write-flash arguments
    (flash_mode, flash_size, offset/binary pairs, etc.).  Relative .bin paths
    are resolved against BUILD_DIR so the command can be run from any CWD.

    Returns:
        list[str]: Flat argument list ready to be appended to an esptool
        command (i.e. everything after ``write-flash``).
    """
    if not os.path.exists(FLASH_ARGS_FILE):
        print(f"ERROR: {FLASH_ARGS_FILE} not found — run 'idf.py build' first",
              file=sys.stderr)
        sys.exit(1)

    with open(FLASH_ARGS_FILE) as f:
        lines = [l.strip() for l in f if l.strip() and not l.startswith("#")]

    args = []
    for line in lines:
        for token in line.split():
            # Prepend BUILD_DIR to relative file paths (*.bin)
            if token.endswith(".bin") and not os.path.isabs(token):
                args.append(os.path.join(BUILD_DIR, token))
            else:
                args.append(token)
    return args


def main():
    """Entry point: parse CLI args, invoke esptool, optionally start monitor.

    Flashing sequence:
      1. Read flash arguments from build/flash_args.
      2. Run esptool with hard-reset before and after flashing.
      3. Unless --no-monitor is given, exec monitor.py with --no-reset so the
         chip's post-flash output is captured without an extra reset pulse.

    Typical usage::

        python3 flash.py                  # flash + watch serial output
        python3 flash.py --no-monitor     # flash only
        python3 flash.py --port /dev/ttyUSB0 --baud 115200
    """
    parser = argparse.ArgumentParser(description="Flash ESP32-S3 firmware")
    parser.add_argument("--port",       default="/dev/ttyACM0")
    parser.add_argument("--baud",       type=int, default=460800)
    parser.add_argument("--no-monitor", action="store_true",
                        help="Don't start serial monitor after flashing")
    args = parser.parse_args()

    flash_args = read_flash_args()

    cmd = [
        IDF_PYTHON, "-m", "esptool",
        "--chip", "esp32s3",
        "-p", args.port,
        "-b", str(args.baud),
        "--before", "default-reset",
        "--after", "hard-reset",
        "write-flash",
    ] + flash_args

    print(f"[flash] Flashing to {args.port} at {args.baud} baud...")
    print(f"[flash] {' '.join(cmd)}", file=sys.stderr)

    result = subprocess.run(cmd)
    if result.returncode != 0:
        print("[flash] esptool failed", file=sys.stderr)
        sys.exit(result.returncode)

    print("[flash] Flash complete.")

    if not args.no_monitor:
        monitor_script = os.path.join(os.path.dirname(__file__), "monitor.py")
        print(f"[flash] Starting monitor on {args.port}...")
        os.execv(sys.executable, [sys.executable, monitor_script,
                                   "--port", args.port, "--no-reset"])


if __name__ == "__main__":
    main()
